[tool.poetry]
name = "turtleme"
version = "0.1.0"
description = ""
authors = ["tliangso <earth78203@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tk = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
